---
title: "Chem211"
subtitle: General Chemistry
author: "Dyllan Uplinger"
geometry: margin = 1in
output:
  pdf_document:
    toc: yes
    highlight: zenburn
  html_notebook:
    toc: yes
mainfont: Arial
fontsize: 12pt
latex_engine: xelatex
header-includes:
   - \usepackage{chemfig}
---

#Chapter 1
Chemistry: The Science of Change

##1.1 The Study of Chemistry
Chemistry is the branch of science that deals with the identification of the substances of which matter is composed; the investigation of their properties and the ways in which they interact, combine, and change; and the use of these processes to form new substances.

Matter is a physical substance in general, as distinct from mind and spirit; (in physics) that which occupies space and possesses rest mass, especially as distinct from energy: 

###Scientific Method
* Ask a Question: The scientific method starts when you ask a question about something that you observe: How, What, When, Who, Which, Why, or Where?

* Construct a Hypothesis: A hypothesis is an educated guess about how things work. It is an attempt to answer your question with an explanation that can be tested.

* Test Your Hypothesis by Doing an Experiment: Your experiment tests whether your prediction is accurate and thus your hypothesis is supported or not. It is important for your experiment to be a fair test. You conduct a fair test by making sure that you change only one factor at a time while keeping all other conditions the same.

* Analyze Your Data and Draw a Conclusion: Once your experiment is complete, you collect your measurements and analyze them to see if they support your hypothesis or not. 

* Communicate Your Results

##1.2 Classification of Matter
###Substances
Substance is a form of matter with definite composition and distinct properties.

Every pure element is a substance.

Every pure compound is a substance.

    Examples Include: salt (sodium chloride), iron, water, mercury, carbon dioxide, oxygen

Substances differ from one another in composition and may be identified by appearance, smell, taste, and other properties.

###Mixtures
Mixture is a physical combination of multiple substances.

* Mixtures are unlike Chemical Compounds:
    + Substances in a mixture can be separated using physical methods such as filtration, freezing, and distillation.
    + There is little or no energy change when a mixture forms.
    + Mixtures have variable compositions, while compounds have a fixed, definite formula.
    + When mixed, individual substances keep their properties in a mixture, while if they form a compound their properties can change.

Homogeneous mixture is a mixture which has uniform composition and properties throughout

    Examples: any gases at equilibrium in a closed space; the hydrocarbons in gasoline; 
    a sugar solution in water at equilibrium; 
    Vinegar Dissolved in Water; Seawater; Apple Juice
    
Heterogeneous mixture is a mixture that does not have uniform composition and properties throughout. 

    Examples: Trail Mix and Chicken Noodle Soup

###States of Matter
* Substances exist as a:
    + Solid
        + Its volume is fixed; it will not expand to fill a container - Unlike gases and plasmas
        + Most solids are incompressible - their volume hardly changes when pressure changes - Unlike gases and plasmas
        + Solids are not fluids, so they cannot flow. Their shapes do not adapt to that of their containers - Unlike liquids, gases, and plasmas
        + Solids are condensed matter, so their volumes are similar to those of liquids, and much smaller than gases and plasmas
    + Liquid
        + Its volume is fixed; It will not expand to fill a container - Unlike gases and plasmas
        + Most liquids are incompressible - Their volume hardly changes when pressure changes - Unlike gases and plasmas
        + Liquids are fluids, so they can flow. Provided there is gravity, their shapes adapt to that of their containers - Unlike solids
        + Liquids are condensed matter, so their volumes are similar to those of solids, and much smaller than gases and plasmas
    + Gas
        + Its volume is not fixed; It will expand to fill a container
        + It is compressible - Its volume changes when pressure changes
        + Gases are fluids, so they can flow. Their shapes adapt to that of their containers
        + The atoms or molecules in a gas are spread much more thinly than the particles in solids and liquids.

They can change from one state to another without changing the chemical identities

##1.3 Properties of Matter

###Quantative Properties
Exists in a range of magnitudes, and can therefore be measured with a number. Measurements of any particular quantitative property are expressed as a specific quantity, referred to as a unit, multiplied by a number.
      
###Qualitative Properties
Properties that are observed and can generally not be measured with a numerical result. 
      
###Physical Properties
A property that can be measured without changing the chemical composition of a substance.

    Examples: Color, Melting/Boint Point, Young's Modulus, Sheer Modulus
    
###Physical Change
Usually reversible change in the physical properties of a substance, as size or shape
    
    Examples: Freezing, Melting, Condensing, Subliming
    
###Chemical Properties
Property or characteristic of a substance that is observed during a reaction in which the chemical composition or identity of the substance is changed

    Examples: Flammability, Corrosiveness
    
###Chemical Changes
Usually irreversible chemical reaction involving the rearrangement of the atoms of one or more substances and a change in their chemical properties or composition, resulting in the formation of at least one new substance

    Examples: Digestion, Combustion, Oxidation

###Extensive Properties
A property that depends upon the amount of material in a sample.

    Examples: Mass; Volume; Size, Weight, Length

###Intensive Properties
A property that does not depend upon the amount of material in a sample.

    Examples: Temperature; Density; Specific Gravity; Molality, Boiling/Melting Point; Odor

##1.4 Scientific Measurement
Measureable Properties are Quantitative and must include a unit

English System Has units such as feet(ft), gallons(gal) and pounds(lbs) (Not typically used outside of the US)

Metric system is used much more common and includes units such as the metere (m), liters(L), and kilgrams(kg)

###SI Base Units
Current Metric System

Base Quantity       Name      Symbol
----------------    ----      ------
Length              Meter     m
Mass                Kilogram  kg
Time                Second    s
Electric Current    Ampere    A
Temperature         Kelvin    K
Amount of Substance Mole      mol
Luminous Intesity   Candela   cd

Prefix  Symbol   Meaning       Example
------  ---      -----------   ---
Tera-    T       $1x10^{12}$
Giga-    G       $1x10^9$
Mega-    M       $1x10^6$
Kilo-    k       $1x10^3$
Deci-    d       $1x10^{-1}$
Centi-   c       $1x10^{-2}$
Milli-   m       $1x10^{-3}$
Micro-   µ       $1x10^{-6}$
Nano-    n       $1x10^{-9}$
Pico-    p       $1x10^{-12}$

\pagebreak

###Mass
Mass is a measure of the amount of matter in an object. Mass is usually measured in grams (g) or kilograms (kg).

Mass measures the quantity of matter regardless of both its location in the universe and the gravitational force applied to it. An object's mass is constant in all circumstances; contrast this with its weight, a force that depends on gravity.

Your mass on the earth and the moon are identical. Your weight on the moon is about one-sixth of your weight on the earth. 

* Kilogram (kg)
    + The kilogram is the SI unit for mass
    + $1000 g = 1 kg$
* Gram (g)
    + In Chemistry it is more common for the gram to be used
    + $1 g = \frac{1}{1000}kg$
* Atomic Mass Unit (amu)
    + AMU is used to express that mass of atoms and molecules
    + $1 amu = 1.6605x10^{-24}g$
    
###Temperature
* Celsius (°C)
    + Freezing Point: 0
    + Boiling Point: 100
* Kelvin (°K) "Absolute Scale"
    + $K=C+273.15$
    + Lowest Possible Temperature is 0K (This is absolute zero)
    + Absoulte 0 is a therotical limit and has not bene achieved but have gotten close to.
* Farenheit (°F)
    + $F = (\frac{9}{5} * C)+32$
    + Freezing Point: 32
    + Boiling Point: 212
    
\pagebreak    
    
###Derived Units
Many quantities require units not included in the base SI units, such as; Voume and Density

* Density
    + Density is the ratio of mass to volume
    + The SI unit is Kilogram per cubic meter ($\frac{kg}{m^3}$)
    + $Density = \frac{Mass}{Volume}$
    + Other Common units include; 
        + $\frac{g}{cm^3}$  (solids)
        + $\frac{g}{mL}$     (liquids)
        + $\frac{g}{L}$      (gases)
* Volume
    + The derived SI unit for volume is the meter cubed $m^3$
    + The more practical unit is the liter(L)
    + $Volume = \frac{Mass}{Density}$
    + $1 dm^3 = 1 L$
    + $1 cm^3 = 1 mL$
    
##1.5 Uncertainty in Measurement

###Accuracy
Tells how close a measurement is to the true value

###Precision
Tells how close a series of replicae measurements are to each other
    + Precision is the same as reproducibility
    
###Types of Numbers
  * Exact:
    + Have Defined Values
  * Inexact
    + Measure by any method besides counting
      
###Signifigant Figues

##1.6 Using Units and Solving Problems

#Chapter 2

#Reference
